name: Flutter Example CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_text_classification:
    runs-on: macOS-13
    defaults:
      run:
        working-directory: ./example/text_classification
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: dart-lang/setup-dart@08de7e0c9a57cb3229b052af11c7f8eae4a845bd
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: 'stable'
      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Flutter Analyze project source
        run: flutter analyze .

      - name: Build Android
        run: flutter build apk

      - name: Build iOS
        run: flutter build ios --no-codesign
